import turtle
wn = turtle.Screen()             
wn.bgcolor("black")

boo = turtle.Turtle()
boo.hideturtle()
boo.color("darkred")
boo.pensize(1)
boo.speed(500)

# moo = turtle.Turtle()  
# moo.penup()
# moo.goto(200, 200)
# moo.color("hotpink")
# moo.pendown()
# moo.pensize(1)
# moo.speed(500)

# shoo = turtle.Turtle()  
# shoo.penup()
# shoo.goto(-200, -200)
# shoo.color("lightgreen")
# shoo.pendown()
# shoo.pensize(1)
# shoo.speed(500)

# too = turtle.Turtle()  
# too.penup()
# too.goto(-200, 200)
# too.color("lightblue")
# too.pendown()
# too.pensize(1)
# too.speed(500)

# zoo = turtle.Turtle()  
# zoo.penup()
# zoo.goto(200, -200)
# zoo.color("purple")
# zoo.pendown()
# zoo.pensize(1)
# zoo.speed(500)

for i in range(150):
 boo.forward(i)
 boo.right(75)
#   moo.forward(i)
#   moo.left(100)
#   moo.left(90)
#   shoo.backward(i)
#   shoo.right(100)
#   shoo.left(50)
#   too.backward(i)
#   too.right(100)
#   too.right(50)
#   zoo.forward(i)
#   zoo.right(100)
#   zoo.left(40)

# jolene = turtle.Turtle()
# jolene.penup()
# jolene.color("yellow")
# jolene.shape("circle")
# jolene.speed(350)
  
# for size in range(8):
#   jolene.forward(150)
#   jolene.stamp()
#   jolene.forward(-150)
#   jolene.right(90)
#   jolene.right(45)

# jolene.hideturtle()

wn.exitonclick()
